mysite_old/dear_diary/urls.py
from django.urls import path

from . import views

app_name = 'dear_diary'

urlpatterns = [
   path('', views.index, name="home"),
   path('add/', views.add, name="add")

]

mysite_old/mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [

    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    # path('', include('polls.urls')),
    path('', include('dear_diary.urls')),
    


]

mysite_old/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    # # ex: /polls/
    # path('', views.index, name='index'),
    # # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),

    #new way generic view defining
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite_old/dear_diary/models.py
from django.db import models

# Create your models here.

class Entry(models.Model):

	text = models.TextField()
	pub_date = models.DateTimeField(auto_now_add=True)
	is_readed = models.BooleanField(default=False)

	def __str__(self):
		return "Entries # {}".format(self.id)

	class Meta:
		verbose_name_plural = 'entries'


class EntrySummarry(Entry):
    class Meta:
        proxy = True
        verbose_name = 'Entry Summary'
        verbose_name_plural = 'Entries Summary'

mysite_old/polls/models.py
from django.db import models

from django.utils import timezone
import datetime
# Create your models here.
# from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


    def was_published_recently(self):
	    now = timezone.now()
	    return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite_old/dear_diary/forms.py
from django.forms import ModelForm
from .models import Entry

class EntryForm(ModelForm):
	class Meta:
		model = Entry
		fields = ('text',)

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		self.fields['text'].widget.attrs.update({'class':'textarea','cols':'100','placeholder':'What do you think ! Please do Entry?'})

mysite_old/dear_diary/views.py
from django.shortcuts import render, redirect
from .models import Entry
# Create your views here.
from .forms import EntryForm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse


def index(request):
	# entries = Entry.objects.all()
	entries = Entry.objects.order_by('-pub_date')

	context= {'entries':entries}
	return render(request,'dear_diary/diary.html', context)

def add(request):
	if request.method == 'POST':
		form = EntryForm(request.POST)
		if form.is_valid():
			form.save()
			# return HttpResponseRedirect(reverse('dear_diary:home'))
			return redirect('dear_diary:home')
	else:
		form = EntryForm()
	context = {'form': form}
	return render(request,'dear_diary/add_entry.html', context)

mysite_old/polls/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse
# from django.template import loader
# from django.http import Http404

from django.views import generic
from django.utils import timezone

# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")
# def index_old(request):#new index  by using template and httpresponse
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     # output = ', '.join([q.question_text for q in latest_question_list])

#     template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     # return HttpResponse(output)
#     return HttpResponse(template.render(context, request))

 # new short cut way

#start commenting working view------
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', context)


# def detail(request, question_id):
# 	# try:
# 	# 	question = Question.objects.get(pk=question_id)
# 	# except Question.DoesNotExist:
# 	# 	raise Http404("Question does not exist")

# 	#other way
# 	question = get_object_or_404(Question, pk=question_id)
# 	return render(request, 'polls/details.html', {'question': question})#HttpResponse("You're looking at question %s." % question_id)

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

#------End the commenting working code-------

#new generic view concept

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

    #new method to perform the testcases
    # def get_queryset(self):
	   #  """
	   #  Return the last five published questions (not including those set to be
	   #  published in the future).
	   #  """
	   #  return Question.objects.filter(
	   #      pub_date__lte=timezone.now()
	   #  ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/details.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/details.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite_old/dear_diary/templates/dear_diary/add_entry.html
{% load static %}

<html>
<head>
	<title>Welcome Diary!</title>
	<link rel="stylesheet" type="text/css" href="{% static 'dear_diary/bootstrap-4.1.0/dist/css/bootstrap.min.css' %}" />
	 
    <!-- <script  type="text/javascript" href="{% static 'dear_diary/js/jquery-min.js' %}" />
    <script  type="text/javascript" href="{% static 'dear_diary/bootstrap-4.1.0/dist/js/bootstrap.min.js' %}" /> -->
</head>
<body>
	<div >
		<div style="background-color: #00cc99;color:white;height: 100px;text-align: left;">
			<h3><p style="padding-left: 20px;padding-top: 25px;">Dear Diary</h3></p>
		</div>
		<br/>
		<br>
		<a href="{% url 'dear_diary:home' %}">Back to All Entries</a>
		<div class="container" style="align-content: center;">
			<h3> Add new Entry</h3>
			<form method="POST" action="{% url 'dear_diary:add' %}">
				{% csrf_token %}
			  <div class="jumbotron">
				{{form.text}}
				<br/>
				<button type="submit" class="btn btn-primary">Submit</button>
				</div>
			 </form>
		</div>
		
	</div>
</body>
<script  type="text/javascript" href="{% static 'dear_diary/js/jquery-min.js' %}" />
    <script  type="text/javascript" href="{% static 'dear_diary/bootstrap-4.1.0/dist/js/bootstrap.min.js' %}" />
</html>

mysite_old/dear_diary/templates/dear_diary/diary.html
{% load static %}

<html>
<head>
	<title>Welcome Diary!</title>
	<link rel="stylesheet" type="text/css" href="{% static 'dear_diary/bootstrap-4.1.0/dist/css/bootstrap.min.css' %}" />
	 
   
</head>
<body>
	<div >
		<div style="background-color: #00cc99;color:white;height: 100px;text-align: left;">
			<h3><p style="padding-left: 20px;padding-top: 25px;">Dear Diary</h3></p>
		</div>
		<br/>
		<br>
		<div style="text-align:center;">
			<h3>All Entries</h3>
		</div>
		<div class="container" style="align-content: center;">
			<a href="{% url 'dear_diary:add' %}">Add new Entry</a>
			&nbsp;&nbsp;<a href="/admin">Visit Admin</a>
			{% for each_entry in entries %}
		  <div class="jumbotron">
		  	<p><strong>Publish date:</strong>{{ each_entry.pub_date }}</p>
<!-- 		    <h1>Bootstrap Tutorial</h1>  -->
		    <p>{{each_entry.text}}</p> 
		  </div>
		  {% endfor %}
		  
		</div>
	</div>
</body>
 <script  type="text/javascript" href="{% static 'dear_diary/js/jquery-min.js' %}" />
    <script  type="text/javascript" href="{% static 'dear_diary/bootstrap-4.1.0/dist/js/bootstrap.min.js' %}" />
</html>

mysite_old/polls/templates/polls/details.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

mysite_old/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
			<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite_old/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>